import markdown
from fpdf import FPDF
import io

class LegalDraftPDF(FPDF):
    def header(self):
        # Optional subtle header
        self.set_font("Times", "I", 10)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, "Generated by Bharat Law GPT", align="R")
        self.ln(15)

        # Watermark (Rotated and faded using light gray)
        self.set_font("Times", "B", 100)
        self.set_text_color(235, 235, 235)  # Very light gray instead of opacity
        
        # Center of the page approx
        with self.rotation(45, 105, 148):
            self.text(40, 150, "DRAFT")
            
        self.set_text_color(0, 0, 0)
        
    def footer(self):
        self.set_y(-15)
        self.set_font("Times", "I", 10)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

def create_pdf(text_content: str) -> bytes:
    # Convert LLM Markdown (## Titles, **Bold**) to HTML
    html_content = markdown.markdown(text_content)
    
    pdf = LegalDraftPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(20, 20, 20)
    
    # Standard legal document styling
    pdf.set_font("Times", size=12)
    
    # fpdf2 allows setting line height for better spacing
    pdf.set_stretching(100)
    
    # Write the HTML content directly onto the PDF
    # The markdown -> html -> fpdf pipeline maintains bold, italics, headers, lists!
    pdf.write_html(html_content)
    
    return bytes(pdf.output())
